name: Super-Linter

on: push

permissions:
  contents: read

jobs:
  super-lint:
    permissions:
      contents: read
      pull-requests: read
      
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
